### ISSUE TITLE
:: $ object '::s' is not of type '::cortex::lang::dispatcher'

### ISSUE THREAD

**Issue by jeffplourde** [cortexlang/web#7]
Issuing the `web::server s: 8000` command and accessing the server on port 8000 yields `:: $ object '::s' is not of type '::cortex::lang::dispatcher'` and a SIG ABORT.  Tried on Mac and Ubuntu x64 with same result.  Captured the stack trace in gdb on Ubuntu...

```sh
(gdb) bt
#0  0x00007ffff7702267 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff7703eca in __GI_abort () at abort.c:89
#2  0x00007ffff7adff98 in cx_criticalv (
    fmt=0x7ffff7b58da8 "object '%s' is not of type '%s'", args=0x7ffff67a6cc0)
    at src/cx_err.c:224
#3  0x00007ffff7ae0597 in cx_critical (
    fmt=0x7ffff7b58da8 "object '%s' is not of type '%s'") at src/cx_err.c:303
#4  0x00007ffff7ae8fd5 in cx_assertType (
    type=0x7ffff7d71a78 <dispatcher.o+120>, o=0x65fe38) at src/cx_object.c:1155
#5  0x00007ffff69c8bd8 in web_handler (conn=0x7ffff0001588, ev=MG_WS_CONNECT)
    at src/web_server.c:205
#6  0x00007ffff69b9528 in call_user (conn=0x7ffff0001580, ev=MG_WS_CONNECT)
    at src/mongoose.c:1804
#7  0x00007ffff69be389 in send_websocket_handshake_if_requested (
    conn=0x7ffff0001588) at src/mongoose.c:3016
#8  0x00007ffff69c3f5a in on_recv_data (conn=0x7ffff0001580)
    at src/mongoose.c:4636
#9  0x00007ffff69c5897 in mg_ev_handler (nc=0x7ffff0000fa0, ev=3, 
    p=0x7ffff67a7540) at src/mongoose.c:5165
#10 0x00007ffff69b6d3e in ns_call (nc=0x7ffff0000fa0, ev=3, p=0x7ffff67a7540)
    at src/mongoose.c:509
#11 0x00007ffff69b7db0 in ns_read_from_socket (conn=0x7ffff0000fa0)
    at src/mongoose.c:938
#12 0x00007ffff69b85c2 in ns_mgr_poll (mgr=0x7ffff00008f0, milli=50)
    at src/mongoose.c:1083
#13 0x00007ffff69c4a24 in mg_poll_server (server=0x7ffff00008f0, 
    milliseconds=50) at src/mongoose.c:4843
#14 0x00007ffff69c8e6a in web_run (data=0x65fe38) at src/web_server.c:284
#15 0x00007ffff70aa6aa in start_thread (arg=0x7ffff67aa700)
---Type <return> to continue, or q <return> to quit---
    at pthread_create.c:333
#16 0x00007ffff77d3eed in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by jeffplourde** [comment]
Thanks!
